audiotracks/urls.py
from django.conf.urls.defaults import *
from audiotracks import feeds

urlpatterns = patterns("audiotracks.views",
    url("^/?$", "index", name="audiotracks"),
    url("^/(?P<page_number>\d+)/?$", "index", name="audiotracks"),
    url("^/track/(?P<track_slug>.*)$", "track_detail", name="track_detail"),
    url("^/upload", "upload_track", name="upload_track"),
    url("^/edit/(?P<track_id>.+)", "edit_track", name="edit_track"),
    url("^/confirm_delete/(?P<track_id>\d+)$", "confirm_delete_track", 
        name="confirm_delete_track"),
    url("^/delete$", "delete_track", name="delete_track"),
    url("^/tracks$", "user_index", name="user_index"),
    url("^/tracks/(?P<page_number>\d)/?$", "user_index", name="user_index"),
    url("^/feed/?$", feeds.choose_feed, name="tracks_feed"),
)

audiotracks/models.py
import os
import mimetypes

from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import slugify
from django.utils.translation  import ugettext_lazy as _

from thumbs import ImageWithThumbsField

def slugify_uniquely(value, obj, slugfield="slug"): 
    suffix = 1
    potential = base = slugify(value)
    filter_params = {}
    filter_params['user'] = obj.user
    while True:
        if suffix > 1:
            potential = "-".join([base, str(suffix)])
        filter_params[slugfield] = potential
        obj_count = obj.__class__.objects.filter(**filter_params).count()
        if not obj_count:
            return potential
        # we hit a conflicting slug, so bump the suffix & try again
        suffix += 1


def get_upload_path(dirname, obj, filename):
    return os.path.join("audiotracks", dirname, obj.user.username, filename)

def get_images_upload_path(obj, filename):
    return get_upload_path("images", obj, filename)

def get_audio_upload_path(obj, filename):
    return get_upload_path("audio_files", obj, filename)


class AbstractTrack(models.Model):

    class Meta:
        abstract = True

    user = models.ForeignKey(User,
        related_name = "tracks",
        blank = True,
        null = True
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    audio_file = models.FileField(_("Audio file"), upload_to=get_audio_upload_path)
    image = ImageWithThumbsField(_("Image"), upload_to=get_images_upload_path, null=True,
            blank=True, sizes=((48,48), (200,200)))
    title = models.CharField(_("Title"), max_length="200", null=True)
    artist = models.CharField(_("Artist"), max_length="200", null=True, blank=True)
    genre = models.CharField(_("Genre"), max_length="200", null=True, blank=True)
    date = models.CharField(_("Date"), max_length="200", null=True, blank=True)
    description = models.TextField(_("Description"), null=True, blank=True)
    slug = models.SlugField(verbose_name=_("Slug (last part of the url)"))
    _original_slug = None # Used to detect slug change

    def __init__(self, *args, **kwargs):
        super(AbstractTrack, self).__init__(*args, **kwargs)
        self._original_slug = self.slug

    def __unicode__(self):
        return "Track '%s' uploaded by '%s'" % (self.title, self.user.username)

    def save(self, **kwargs):
        if not self.slug:
            # Automatically set initial slug
            slug_source = getattr(self, 'title') or \
                    os.path.splitext(os.path.basename(self.audio_file.name))[0]
            self.slug = slugify_uniquely(slug_source, self)
        super(AbstractTrack, self).save(**kwargs)

    @property
    def mimetype(self):
        return mimetypes.guess_type(self.audio_file.path)[0]

    @models.permalink
    def get_absolute_url(self):
        return ('audiotracks.views.track_detail', [self.user.username, self.slug])

if hasattr(settings, 'AUDIOTRACKS_MODEL'):
    app_name, model_name = settings.AUDIOTRACKS_MODEL.split('.')
    Track = models.get_model(app_name, model_name)
else:
    class Track(AbstractTrack):
        pass

audiotracks/templates/audiotracks/_list_actions.html
{% load i18n %}
  <a class="btn small btn-primary" href="{% url edit_track track.id %}">{% trans 'Edit' %}</a>
  <a class="btn small btn-danger" href="{% url confirm_delete_track track.id %}">{% trans 'Delete' %}</a>

audiotracks/templates/audiotracks/base.html
{% load i18n %} 
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>django-audiotracks example project</title>
    <style>
      label { display: block; }
      .audiotracks-edit-row { clear:both; margin-bottom: 1em; }
      .audiotracks-edit-row > div { float: left; margin-right: 1em; }
      .audiotracks-form { margin-bottom: 1em; }
      .audiotracks-delete-image-label { display: inline; }
      .messages { color: green; border: solid 1px green; padding: 0.2em; }
      .messages li { list-style: none; }
      .errorlist { color: red; list-style: none; display: inline; }
    </style>
  </head>
  <body>

  {% block subnav %}
      {% if user.is_authenticated %}
          <ul>
            <li><a href="{% url audiotracks %}">{% trans 'Latest tracks' %}</a></li>
            <li><a href="{% url user_index user.username %}">{% trans 'Your tracks' %}</a></li>
            <li><a href="{% url upload_track %}">{% trans 'Upload track' %}</a></li>
          </ul>
      {% else %}
          &nbsp;
      {% endif %}
  {% endblock %}

  {% if messages %}
  <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
  </ul>
  {% endif %}

  {% block body %}
  {% endblock %}
  </body>
</html>

audiotracks/templates/audiotracks/confirm_delete.html
{% extends "audiotracks/base.html" %}
{% load i18n %}

{% block body %}
{% if user.is_authenticated %}
<div class="audiotracks-form">
  <p>
  {% blocktrans with track.title as title %}Are you sure you want to delete "{{ title }}"? This can't be undone.{% endblocktrans %}
  </p>
  <form method="POST" action="{% url delete_track %}">
    {% csrf_token %}
    <input type="hidden" name="track_id" value="{{ track.id }}">
    <input type="hidden" name="came_from" value="{{ came_from }}">
    <button class="btn btn-danger">{% trans 'Yes, delete this track' %}</button>
  </form>
</div>
{% endif %}
{% endblock %}

audiotracks/templates/audiotracks/detail.html
{% extends "audiotracks/base.html" %}
{% load i18n %}

{% block body %}
<div class="audiotracks-detail">
  <img src="{{ track.image.url_200x200 }}" />
  <h1>
    {{ track.title }}
  </h1>
  <h2>
    {% if track.artist %}by {{ track.artist }}{% endif %}
    {% if track.date %}, {{ track.date }}{% endif %}
  </h2>
  {% if track.genre %}
  <h3>
     Genre: {{ track.genre }} 
  </h3>
  {% endif %}
  <div>
    <audio src="{{ track.audio_file.url }}" controls="controls">
      Your browser does not support the audio element.  Maybe you should
      consider using <a href="http://www.mozilla.com/firefox/">Firefox</a>, <a
        href="http://www.google.com/chrome">Chrome</a> or <a
        href="http://www.opera.com/browser/">Opera</a>.
    </audio>
  </div>
  <div class="audiotracks-description">
    {{ track.description }}
  </div>
  <div class="audiotracks-download">
    <a class="btn btn-large btn-success" href="{{ track.audio_file.url }}">{% trans 'Download Track' %}</a>
  </div>
{% if track.user == request.user %}
<p>
  <a class="btn btn-primary" href="{% url edit_track track.id %}">{% trans 'Edit' %}</a>
  <a class="btn btn-danger" href="{% url confirm_delete_track track.id %}">{% trans 'Delete' %}</a>
</p>
{% endif %}
</div>
{% endblock %}

audiotracks/templates/audiotracks/edit.html
{% extends "audiotracks/base.html" %}
{% load i18n %}

{% block body %}
{% if user.is_authenticated %}
<div class="audiotracks-form">
  <form class="form-stacked" method="POST" enctype="multipart/form-data" 
    action="{% url edit_track track.id %}">
    {% csrf_token %}
    <fieldset>
      <legend>{% trans 'Edit track' %}</legend>
      {{ form.non_field_errors }}
      <div class="audiotracks-edit-row">
        {{ form.audio_file.errors }}
        <label class="top" for="id_audio_file">{{ form.audio_file.label }}</label>
        {{ form.audio_file }}
        <span class="audiotracks-edit-current-data">{{ track_filename }}</span>
      </div>
      <div class="audiotracks-edit-row">
        {{ form.image.errors }}
        <label class="top" for="id_image">{{ form.image.label }}</label>
        {{ form.image }}
        {% if track.image %}
          <img src="{{ track.image.url_48x48 }}" alt="Track image">
          <input type="checkbox" name="delete_image" value="1"
          id="delete_image">
          <label id="audiotracks-delete-image-label" for="delete_image">{% trans 'Delete image' %}</label>
        {% endif %}
      </div>
      <div class="audiotracks-edit-row">
        <div class="audiotracks-edit-half-row">
          {{ form.title.errors }}
          <label for="id_title">{{ form.title.label }}</label>
          {{ form.title }}
        </div>
        <div class="audiotracks-edit-half-row">
          {{ form.artist.errors }}
          <label for="id_artist">{{ form.artist.label }}</label>
          {{ form.artist }}
        </div>
      </div>
      <div class="audiotracks-edit-row">
        <div class="audiotracks-edit-half-row">
          {{ form.genre.errors }}
          <label for="id_genre">{{ form.genre.label }}</label>
          {{ form.genre }}
        </div>
        <div class="audiotracks-edit-half-row">
          {{ form.date.errors }}
          <label for="id_date">{{ form.date.label }}</label>
          {{ form.date }}
        </div>
      </div>
      <div class="audiotracks-edit-row">
        {{ form.tags.errors }}
        <label for="id_tags">{{ form.tags.label }}</label>
        {{ form.tags }}
      </div>
      <div class="audiotracks-edit-row">
        {{ form.description.errors }}
        <label class="top" for="id_description">{{ form.description.label }}</label>
        {{ form.description }}
      </div>
      <div id="slug" class="audiotracks-edit-row">
        {{ form.slug.errors }}
        <label for="id_slug">{{ form.slug.label }}</label>
        <div class="input-prepend">
          <span class="audiotracks-edit-current-data add-on">{{ track_url_prefix }}</span>{{ form.slug }}
        </div>
      </div>
      <p id="save-button">
      <button class="btn btn-primary">{% trans 'Save your changes' %}</button>
      </p>
    </fieldset>
  </form>
</div>
<div class="audiotracks-form" id="delete-form">
  <form action="{% url confirm_delete_track track.id %}">
    <p id="delete-button">
    <button class="btn btn-danger">{% trans 'Delete this track' %}</button>
    </p>
  </form>
</div>
{% endif %}
{% endblock %}

audiotracks/templates/audiotracks/latest.html
{% extends "audiotracks/base.html" %}
{% load i18n %}

{% block body %}
<h1>{% trans 'Latest Tracks' %}</h1>
<ul class="audiotracks-list">
{% for track in tracks %}
<li>
{% if track.user == request.user %}
    {% include 'audiotracks/_list_actions.html' %}
{% endif %}
<a href="{% url track_detail track.user.username,track.slug %}">{{ track.title }}</a>
uploaded by {{ track.user.username }}
on {{ track.created_at|date:"l d M Y" }}
</li>
{% endfor %}
</ul>

{% include '_pagination.html' %}

{% endblock %}

audiotracks/templates/audiotracks/new.html
{% extends "audiotracks/base.html" %}
{% load i18n %}

{% block body %}
{% if user.is_authenticated %}
<form class="audiotracks-form" id="audiotracks-upload-form" 
      method="POST" enctype="multipart/form-data" action="{% url upload_track %}">
  {% csrf_token %}
  <fieldset>
    <legend>{% trans 'Upload a new track' %}</legend>
    {{ form.as_p }}
  </fieldset>
  <p>
  <button class="btn primary">{% trans 'Upload' %}</button>
  </p>
</form>
{% endif %}
{% endblock %}

audiotracks/templates/audiotracks/user_index.html
{% extends "audiotracks/base.html" %}
{% load i18n %}

{% block body %}
<h1>{% trans 'Your Tracks' %}</h1>
<ul class="audiotracks-list">
{% for track in tracks %}
<li>
    {% include 'audiotracks/_list_actions.html' %}
<a href="{% url track_detail username,track.slug %}">{{ track.title }}</a>
{% blocktrans with track.updated_at|timesince as last_modified %}last modified {{ last_modified }} ago{% endblocktrans %}
</li>
{% endfor %}
</ul>

{% include '_pagination.html' %}

{% endblock %}